### ISSUE TITLE
"pmc_square_plot" calculation

### ISSUE THREAD

**Issue by dongbohu** [greenelab/preprint-similarity-search#100]
@danich1: Two questions:
1. Can we delete this line?
https://github.com/greenelab/preprint-similarity-search/blob/e7082c44e51c26f9282f6071b89b9e92526a9465/server/auto_updater/embedding_bin_updater.py#L200
If I understand correctly, `bin_words` is the set of all unique words in current bin, `background_words` is the set of all words, so the former should be always a subset of the latter.

2. Should `bin_sum` be calculated right after this `if` block? https://github.com/greenelab/preprint-similarity-search/blob/e7082c44e51c26f9282f6071b89b9e92526a9465/server/auto_updater/embedding_bin_updater.py#L194-L195
because `bin_dict` may be changed by the two line above.

**Comment by danich1** [comment]
>If I understand correctly, bin_words is the set of all unique words in current bin, background_words is the set of all words, so the former should be always a subset of the latter.

Correct. The only reason I have that line is to filter out tokens within bin_word counts that arent in the background and vice versa. If this line is removed than there might be a potential waste of computational resourcess (very minor but its there)

>Should bin_sum be calculated right after this if block? 

Well I precalculated bin_sum before the word filtering (check line 287) to keep that variable as the sum of all tokens within a bin. I guess in the grand scheme it doesn't really matter. We could move bin sum after the if statement if desired.

**Comment by dongbohu** [comment]
> The only reason I have that line is to filter out tokens within bin_word counts that arent in the background and vice versa. If this line is removed than there might be a potential waste of computational resourcess (very minor but its there)

Thanks. But `background_words` includes all unique tokens in `global_word_count_file`:
https://github.com/greenelab/preprint-similarity-search/blob/e7082c44e51c26f9282f6071b89b9e92526a9465/server/auto_updater/dataset_updater.py#L71
How could a word that's in `bin_words` possibly be *NOT* in `background_words`?

**Comment by dongbohu** [comment]
> Well I precalculated bin_sum before the word filtering (check line 287) to keep that variable ...

Sorry,what I meant was whether it makes more sense scientifically to RE-calculate `bin_sum` when `bin_dict` was changed by that `if` statement. (I know the effect may be very minor).

**Comment by danich1** [comment]
>How could a word that's in bin_words possibly be NOT in background_words?

Ah right! I forgot that everything is within the global word_count_file. Yup, ignore my explanation and feel free to remove that line. If you do remove that line make sure to change the for loop to loop over bin_words

>Sorry,what I meant was whether it makes more sense scientifically to RE-calculate bin_sum when bin_dict was changed by that if statement. (I know the effect may be very minor).

Yeah would be correct to recalculate bin_sum after filtering out words from the dictionary. Just to be through.

**Comment by dongbohu** [comment]
Thanks @danich1! I will generate a new json plot file based on the changes above.
