### ISSUE TITLE
BioRxiv DOIs not working for Website

### ISSUE THREAD

**Issue by danich1** [greenelab/preprint-similarity-search#72]
@vincerubinetti is working on a twitter [preprintbot](https://github.com/greenelab/preprint-bot) and encountered a few dois that produced errors on our website. [Log here](https://github.com/greenelab/preprint-bot/runs/1901610199?check_suite_focus=true). Upon further inspection it turns out these errors arose on bioRxiv's end rather than ours. [Link Example Here](http://api.biorxiv.org/details/10.1101/2021.01.06.425392). This also raises a few points to be discussed:

1. Should we return more specific error messages besides cant get results?
2. Is there a way to create cron jobs to automatically update our Pubmed Central Landscape? #73 
3. We need to update the README.md to include instructions on how to update the visualization/retrain word2vec model #74

**Comment by vincerubinetti** [comment]
Maybe we should also have some kind of notification (slack? sentry?) of when servers or down, either ours or upstream. Our app hasn't been working for > 24 hours and we didn't know it.

**Comment by cgreene** [comment]
This works:
http://api.biorxiv.org/details/biorxiv/10.1101/2021.01.06.425392

Is the URL example above right?

**Comment by danich1** [comment]
>This works:
>http://api.biorxiv.org/details/biorxiv/10.1101/2021.01.06.425392
>
>Is the URL example above right?

My above link is missing biorxiv in the url. That's whats causing the issue. The link you provided is the correct version.
