### ISSUE TITLE
Cron Job for Autoupdating PubMed Central OA Embeddings

### ISSUE THREAD

**Issue by danich1** [greenelab/preprint-similarity-search#73]
As mentioned in #72, it would be ideal to create a pipeline that auto updates our preprint embeddings with newly published papers. Our current model is outdated by a year and for sustainability we should enable this feature. 
Ideally I'm thinking the pipeline will be the following:

1. Bulk Download/Scan through files within this [ftp link](https://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_bulk/).
2. Extract files not in our current repository
3. Embed these missing files 
4. Add the files into our nearest neighbor database

Let me know your initial thoughts @dongbohu. I have a feeling that this shouldn't be too hard to accomplish since the first step can be [streamed online](https://stackoverflow.com/questions/18617244/read-contents-of-tar-gz-file-from-website-into-a-python-3-x-object).

**Comment by dongbohu** [comment]
@danich1: Steps 1, 2 and 4 should be easy. How hard is step 3? How long does this step take roughly?

**Comment by danich1** [comment]
Won't take long. It's basically indexing a matrix, so roughly linear time (~1-2 min) for each document and that's an overestimate to be honest.

**Comment by dongbohu** [comment]
@danich1: If you write a program to embed the missing files, I can integrate it into a cron job on the API production server.

**Comment by danich1** [comment]
>If you write a program to embed the missing files, I can integrate it into a cron job on the API production server.

Sounds good. PR should be coming this week. I'll assign you as a reviewer.

**Comment by cgreene** [comment]
Do we want to _update the embeddings_ or put _new papers into the current embeddings_? I think the latter would be the automated bit. The former, we might want to check more carefully. What do you think?

**Comment by dongbohu** [comment]
I agree that the latter will be much easier.

**Comment by danich1** [comment]
Yeah the latter is much easier, we should go down that route.

**Comment by dongbohu** [comment]
Done in PR #103.
