### ISSUE TITLE
Add timeout to endpoint?

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/preprint-similarity-search#75]
Certain DOI's seem to stall the main endpoint for this server, like this one:

https://api-pss.greenelab.com/doi/10.1101/2021.01.15.426911

For the sake of the web app and the twitter bot, we should have a (server-side) timeout for this (5 minutes?)

**Comment by dongbohu** [comment]
@danich1: I ran `extract_text_to_fp()` manually on `10.1101/2021.01.15.426911`. It took 27 minutes on the Google Cloud virtual machine. I know this is a long paper, but it still took much longer than I expected:-(

**Comment by vincerubinetti** [comment]
You mentioned there is already a time out of 5 minutes, but I'm guessing since this doi takes so long, that timeout only applies to a certain part of the processing?  Is there a way to set a hard timeout such that it returns an error if the final json result hasn't happened in 5 minutes.

**Comment by dongbohu** [comment]
The current timeout value of 5 minutes is set by the app server, not the app. We need to have a more granular timeout value inside the app.

**Comment by danich1** [comment]
@dongbohu: That's not good. I'm currently seeing if we can use a different package or find a new way to improve pdf parsing.

**Comment by danich1** [comment]
Update: I have successfully turn 27 min -> 17 seconds. Had to switch libraries. PR coming up shortly.

**Comment by vincerubinetti** [comment]
> Update: I have successfully turn 27 min -> 17 seconds. Had to switch libraries. PR coming up shortly.

Wow!

> The current timeout value of 5 minutes is set by the app server, not the app. We need to have a more granular timeout value inside the app.

When you say "app", you're talking about a piece of the backend (I don't know backend terminology well), not the webapp?

@danich1 Although you fixed this specific pdf conversion (?) problem, could we still add a hard timeout for the whole backend process in case there are any other unexpected errors?

**Comment by danich1** [comment]
>@danich1 Although you fixed this specific pdf conversion (?) problem, could we still add a hard timeout for the whole backend process in case there are any other unexpected errors?

Yeah I'm fine with this update; however, @dongbohu knows how to implement that better than me. I'll open the PR and let him direct me on how to implement this feature.

**Comment by dongbohu** [comment]
Timeout of 4 min added inside the app in #79.
