### ISSUE TITLE
Preprint classified in odd way

### ISSUE THREAD

**Issue by byrdjb** [greenelab/preprint-similarity-search#82]
{{ date | date('dddd, MMMM Do YYYY, h:mm a') }}

https://api-pss.greenelab.com/doi/10.1101/833400

I've got this old preprint that I've meaning to submit somewhere, and I tried the tool.
https://www.biorxiv.org/content/10.1101/308726v3

Output was fairly random-looking.

![pyUYOy-f](https://user-images.githubusercontent.com/29103037/110127310-7d40df00-7d93-11eb-92c2-25b7afd94752.jpg)

**Comment by dongbohu** [comment]
@byrdjb: Thank you for reporting the issue. We looked at the PDF output and it appears there are some formatting and other tokens, so we're implementing a solution to use XML first if available falling back to PDF if unavailable. When that gets deployed we can try your preprint again.

**Comment by byrdjb** [comment]
Thank you!

**Comment by dongbohu** [comment]
@byrdjb We deployed the parser with XML. Can you check your paper again? Thanks.

**Comment by byrdjb** [comment]
@dongbohu Great work--the randomness seems to be resolved. Thank you!

**Comment by dongbohu** [comment]
Thanks @byrdjb. I am closing this issue now.
